global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: ‘node’
    static_configs:
      - targets: [‘nodeexporter:9100’]

  - job_name: ‘cadvisor’
    static_configs:
      - targets: [‘cadvisor:8080’]